### ISSUE TITLE
Web RFID errors

### ISSUE THREAD

**Issue by jezza323** [esitarski/CrossMgr#119]
**Describe the bug**
HTTP Post to /rfid.js returns an error and RFID read is not applied to the race

**To Reproduce**
Enable RFID, using Web and send HTTP POST to /rfid.js endpoint at the web port

**Expected behavior**
Should return a 200 or 201 response and RFID tags/times should be applied to the race

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CrossMgr v3.1.17-20230314101703

**Additional context**
Tested with HTTP POST from Postman and from custom app.

**Comment by jezza323** [comment]
Identified missing import in Webserver.py, PR submitted #117

**Comment by esitarski** [comment]
Issue addressed in main branch.  Fix available in release.
