### ISSUE TITLE
Delay to reads from RFID reader displaying in "recorded" pane

### ISSUE THREAD

**Issue by moth754** [esitarski/CrossMgr#127]
Upon reading a tag, the correct time appears next to the correct participant in the results view. However it takes between 5 secs and 3 min for the read to appear in the recorded pane. Sometimes not appearing until another chip is read.

Read is an Impinj Speedway R420 connected to a Dell Latitude 5420 Rugged running windows 11 (build 22631) via an ethernet cable. both the PC and reader have static IPs. Antivirus and firewall off.

CrossMgr versions 3.1.39

**Comment by esitarski** [comment]
There is usually a 2-3 second delay between the reads and the display update, however, I have not heard of or seen such a long delay.
How much memory does the Dell 5420 have?
Let me know.  Thanks.

**Comment by moth754** [comment]
32GB - after further experimentation, the culprit appears to be windows firewall and a slow router. Adding multiple rules (for each CrossMgr component) and upgrading the router have worked wonders

**Comment by esitarski** [comment]
Glad to hear that you got this figured out.
