### ISSUE TITLE
What license of CrossMgr

### ISSUE THREAD

**Issue by key** [esitarski/CrossMgr#2]
I'm lap timing app developer, and interested in this package.
Let me know about license of CrossMgr.

**Comment by esitarski** [comment]
Can you be more specific?
Do you want to use the package to get race results, or do you want to contribute to the project?
Thanks.

**Comment by key** [comment]
sorry for late reply.

I want to use crossmgr with mylaps decoder.
Mylaps uses proprietary protocol so I can't decide to use this.

I think I use crossmgr and mylaps if crossmgr is provided by bsd like license. (I can contribute codes if I find own source mylaps protocol parser)

**Comment by mbuckaway** [comment]
License file added to repo.
