### ISSUE TITLE
CrossMgrImpinj remember report method

### ISSUE THREAD

**Issue by rkantos** [esitarski/CrossMgr#20]
I’ve started experimenting with Motorola FX7400 and FX9500 RFID-readers, and as it is, they only support “First Red Time” Report method with CrossMgrImpinj. Could we get CrossMgrImpinj to remember this feature as now I have to change it everytime I use a Motorola reader.

**Comment by esitarski** [comment]
Fixed in CrossMgrImpinj 3.0.0.
