### ISSUE TITLE
CrossMgr Help does not work

### ISSUE THREAD

**Issue by mbuckaway** [esitarski/CrossMgr#51]
**Describe the bug**
Help->Help returns and error page:

        <h1>Error response</h1>
        <p>Error code: 404</p>
        <p>Message: File Not Found: /Actions.html [Errno 2] No such file or directory: '/Applications/CrossMgr.app/Contents/Resources/CrossMgrHtmlDoc/Actions.html'

**To Reproduce**
1. Go to Help menu
2. Click on Help

**Desktop (please complete the following information):**
 - happens on Linux and Mac versions (probably windows too)

**Additional context**
Would appear the build is broken and not building help. Happens on the current beta release. Additionally, the current beta release also does not display the icon in the DMG image for crossmgr, but it does work correctly.

**Comment by esitarski** [comment]
Build fixed.  Can you retest with the latest?
