### ISSUE TITLE
Start a race in the past

### ISSUE THREAD

**Issue by mbuckaway** [esitarski/CrossMgr#57]
**Is your feature request related to a problem? Please describe.**
The situation: a road and gravel race. Everyone lines up at the start. The finish line is not at the same location. In fact, it could be 50kms away. The "start line" may not even be a line. The race is started and riders are sent on their way. At the same, everyone has signed in on a sign in sheet, so we know exactly who is supposed to be in the race. Their could have been multiple start waves. We don't want to pull out the entire timing rig to be able record who rode over the start line as we can just assume the sign in sheet is the start list. We can update the excel spreadsheet with who actually DNS'd. We record the start times of the start ways before we head over to the finish line. However, we will setup the timing rig at the finish line to record the riders either manually or via timing chips. 

**Describe the solution you'd like**
We want to be able to start the race in the past from the finish line. The idea is, we would like to be able to set the start time in CrossMgr for each start way. We would have the race time start from that point when the start button is pushed. We have to be able to program in the start time for each way because we cannot guarantee that each way is spaced exactly 15 mins or whatever.

The fun part of this, is that the race would appear to be only one lap....and the first time the rider crosses the line is the only time they would.

This is the kind of thing that happens at P2A and the Hell of the North. HOTN could have timing at the start, but it's Ed Veal's race and it never goes as planned. I would imagine this is what would happen at alot of point to point races.

An alternative, have some way to capture the start remotely (way more effort).

**Describe alternatives you've considered**
Use RaceTiming's software which does the above and the remote start capture.

**Comment by esitarski** [comment]
This feature already exists.
After starting the CrossMgr race, do "Tools/Change Race Start Time...".
Enter the actual race start time in the dialog.

This allows races to be "started" without any equipment set up, or the timer even present.
