### ISSUE TITLE
"Random Start" TT mode

### ISSUE THREAD

**Issue by mbuckaway** [esitarski/CrossMgr#62]
**Is your feature request related to a problem? Please describe.**
Give 'normal' TT's aren't happening, I have to wonder if it is possible or how CrossMgr could be changed to handle TT starts at "random". Basically, riders should show up to the line whenever, and be given the start signal. Timing chips could be used to capture the finish or someone could capture the finish time (click a button?). The idea is that riders just start when they like, that there is never more than 1-4 riders in a group at the start any one time and it doesn't matter when they start. We could say the TT happens from say 6pm-8pm, which small groups or riders set to ride in 10 min intervals (or whatever). The clock would be switched on at 6pm and off at 8pm, with times recorded with whoever did the ride.

**Describe alternatives you've considered**
Manually timing could be used, but the idea is one person could setup the computer equipment, and send the riders off. If chip timing is used, then the finish does not need to be monitored. Another alternative, is to setup X number of riders in a start group going off on minute intervals, with Y number of minutes buffer between them. Riders could be booked say on 10 or 15 min start intervals for the 2 hr TT time slot.

**Comment by esitarski** [comment]
CrossMgr already does this.
If you start in TT mode without a start list, the first entry starts the rider's clock.
Subsequent entries record the laps (if multi-lap) and, of course, the finish.

You can start multiple riders at once by entering all the bib numbers in the Bib field - comma (or space) separated.  When you hit Enter, all the bib numbers get the same start time.

Riders in the same category are ranked together as usual regardless of their start time.

Riders can be started individually, or in small groups.  You can monitor the number of riders on course by looking at the "On Course" display on the Record page.  This makes it easy to respect a course maximum.

If the TT is multi-lap, riders will have to keep track of their own laps, and, there is no bell.  Races must have a lap count (not by time).

Such a scenario could be used for TT, of course, but also as a modified CX or MTB races.  Cycling tracks are now open in some regions (eg. Ontario).  With respect for a course maximum, small start groups (< 5),  online registration and online results (touchless), this could meet the requirements.

Am I missing something?

**Comment by esitarski** [comment]
At present, the Ontario Cycling Association (OCA) explicitly prohibits events as described above (see [here](https://www.ontariocycling.org/forms/oca-return-to-cycling-update-may-29-2020/)):

> Activities CANNOT be structured to have groups [five or less] arrive and participate at
> different start times within the same activity. As example, hosting a time trial type of
> activity over a 4- hour period where five or less participants arrive every 30 minutes to
> complete their effort and depart prior to the next group arriving. The total
> accumulation of all participants [5 each half-hour] would violate the provincial
> regulations of “an organized public event of more than five people” regardless if no
> more than five people are present at any one time. 

Can others comment on the policies in other regions?

**Comment by mbuckaway** [comment]
Thank you for the information, however, I am quite aware of the OCA guidelines. Not sure how a feature request somehow turned into a request to run a unsanctioned event. I'd prefer that such information be discussed in the google group and not in an issue.
