### ISSUE TITLE
Failed to execute script CrossMgr - Windows .exe

### ISSUE THREAD

**Issue by ChainGangEvents** [esitarski/CrossMgr#71]
Upgraded from V3.0.58-20201104092209 to V3.0.62-20210325140204 (Windows .exe version) After installation got fatal error message "Failed to execute script CrossMgr"

**Comment by iwismer** [comment]
I get the same error: Windows logs: 
[CrossMgr_win.log](https://github.com/esitarski/CrossMgr/files/6409728/CrossMgr_win.log)

I also can't launch the version on master on linux or the latest appimage:
[CrossMgr.log](https://github.com/esitarski/CrossMgr/files/6409731/CrossMgr.log)

**Comment by ChainGangEvents** [comment]
New update CrossMgr_V3.0.65-20210501145300 downloaded and it worked. Thank you
