### ISSUE TITLE
"Localhost" share not possible

### ISSUE THREAD

**Issue by ChainGangEvents** [esitarski/CrossMgr#74]
Try to share DB access to another laptop on same network, but no access granted. Changed "Localhost" with main laptop ip address, but still no access possible.

**Comment by mbuckaway** [comment]
Are you using the docker container for the database? Is this what you are attempting to share? If so, by default, the port for the database is not exposed to local network and only to the docker network (with RaceDB).

**Comment by cclague** [comment]
Do you actually want to share access to the database or do you mean to RaceDB?

**Comment by mbuckaway** [comment]
@cclague has a point....about the only reason I can see another system would want DB access is for backup/replication.

**Comment by ChainGangEvents** [comment]
Access to the RaceDB. For example to capture data on another laptop but o the same database.
