### ISSUE TITLE
MTB Enduro Races

### ISSUE THREAD

**Issue by ChainGangEvents** [esitarski/CrossMgr#87]
It would be great to use CrossMgr to time Enduro races, but then the option to exclude certain laps (non-timed sections) from the overall time will have to be possible. In the Categories section next to the Race Laps, another column for lap times to be excluded?

**Comment by JonRosenSystems** [comment]
I've used it successfully to time a 5-stage Enduro.  Run CrossMgr with a separate race for each stage, and then use SeriesMgr to produce the results from all 5 stages.  I did it using J-Chip active RFID equipment; 10 mats and receivers (one for each top and bottom section)  We used a USB drive to collect the results from each receiver and import them into each race for CrossMgr.
